spring.application.name=store-management
server.port=8081

keycloak.auth-server-url=http://localhost:28081/auth/realms/
keycloak.admin-server-url=http://localhost:28081/auth/admin/realms/
keycloak.master-realm=master
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli
keycloak.app-realm=store

pagination.pageNumber=1
pagination.paegSize=20
